config/routes.rb
Rails.application.routes.draw do

  # ユーザー管理
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }
  resources :users, only: [:show]


  # 管理人用
  devise_for :admins
  namespace :admin do
    root to: 'admin/products#index'
    resources :products
  end


  # トップページ/詳細ページ/お気に入り
  root to: 'products#index'
  resources :products, only: [:index, :show] do
    resource :likes, only: [:create, :destroy]
  end

  
  # カート
  resources :carts, only: [:index] do
    collection do
      post :add
    end
    member do
      resources :cart_items, only: [:update, :destroy]
    end
  end


  # 購入
  resources :orders, only: [:new, :create]

end

app/models/product.rb
class Product < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to       :made_in
  has_one_attached :image
  has_many         :cart_items
  has_many         :likes, dependent: :destroy
  has_one          :order

  with_options presence: true do
    validates :name
    validates :price, format: { with: /\A[0-9]+\z/, message: '半角数字で入力してください' }
    validates :title
    validates :explanation
    validates :volume
    validates :ingredient
    validates :image
  end

  validates :made_in_id, numericality: { other_than: 1 }

  def liked?(user)
    likes.where(user_id: user.id).exists?
 end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :title, :explanation, :volume, :ingredient, :image, :made_in_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.order('created_at DESC')
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_footer.html.erb
<footer>
  <div class="admin-footer">
    <% if admin_signed_in? %>
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"admin-logout" %>
    <% end %>
  </div>
</footer>

app/views/admin/products/_header.html.erb
<header>
  <div class="admin-header">
    <% if admin_signed_in? %>
      <%= link_to '管理者用メニューTOP', admin_products_path, class:"admin-logo" %>
      <%= link_to 'ページを確認する', products_path, class:"admin-link", target: "_blank" %>
    <% end %>
  </div>
</header>

app/views/admin/products/edit.html.erb
<%= render 'header' %>
<main>
  <div class="form-wrap">
    <h2>商品の登録</h2>
    <%= form_with model: [:admin, @product], local: true do |f| %>
    <div class="form-colmn">
      <div class="forms">
        <div class="form">
          <%= f.label :name, '商品名' %>
          <%= f.text_field :name, class: "item-string" %>
        </div>
        <div class="form">
          <%= f.label :title, 'キャッチコピー' %>
          <%= f.text_field :title, class: "item-string" %>
        </div>
        <div class="form-half">
          <div class="form">
            <%= f.label :price, '価格' %>
            <%= f.text_field :price, class: "item-string half" %>
          </div>
          <div class="form">
            <%= f.label :volume, '内容量' %>
            <%= f.text_field :volume, class: "item-string half" %>
          </div>
        </div>
        <div class="form">
          <%= f.label :explanation, '商品説明' %>
          <%= f.text_area  :explanation, class: "item-text" %>
        </div>
        <div class="form">
          <%= f.label :ingredient, '成分' %>
          <%= f.text_area  :ingredient, class: "item-text" %>
        </div>
        <div class="form">
          <%= f.label :made_in_id, '原産国' %>
          <%= f.collection_select(:made_in_id, MadeIn.all, :id, :name, {}, {class: "item-select"}) %>
        </div>
        <div class="form">
          <%= f.label :image, "商品画像アップロード", class:"image-btn" %>
          <%= f.file_field :image, class: "item-image" %>
        </div>
        <div class="submit">
          <%= f.submit "登録する", class:"submit-btn" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</main>
<%= render 'footer' %>

app/views/admin/products/index.html.erb
<%= render 'header' %>
<main>
  <ul class="admin-menu">
    <%= link_to '商品登録', new_admin_product_path, class: "admin-list" %>
    <%= link_to '注文履歴', '#', class: "admin-list" %>
    <div class="admin-index">
      <p class="admin-label">< 商品一覧 ></p>
      <% @products.each do |product| %>
      <li class="admin-product">
        <div class="admin-info">
          <p class="admin-name"><%= product.name %></p>
          <div class="admin-btns">
            <%= link_to '編集', edit_admin_product_path(product.id), class: "admin-edit" %>
            <%= link_to '削除', admin_product_path(product.id), method: :delete, class: "admin-destroy", data: {confirm: "削除しますか？"}  %>
          </div>
        </div>
      </li>
      <% end %>
    </div>
  </ul>
</main>
<%= render 'footer' %>

app/views/admin/products/new.html.erb
<%= render 'header' %>
<main>
  <div class="form-wrap">
    <h2>商品の登録</h2>
    <%= form_with model: [:admin, @product], local: true do |f| %>
    <div class="form-colmn">
      <div class="forms">
        <div class="form">
          <%= f.label :name, '商品名' %>
          <%= f.text_field :name, class: "item-string" %>
        </div>
        <div class="form">
          <%= f.label :title, 'キャッチコピー' %>
          <%= f.text_field :title, class: "item-string" %>
        </div>
        <div class="form-half">
          <div class="form">
            <%= f.label :price, '価格' %>
            <%= f.text_field :price, class: "item-string half" %>
          </div>
          <div class="form">
            <%= f.label :volume, '内容量' %>
            <%= f.text_field :volume, class: "item-string half" %>
          </div>
        </div>
        <div class="form">
          <%= f.label :explanation, '商品説明' %>
          <%= f.text_area :explanation, class: "item-text" %>
        </div>
        <div class="form">
          <%= f.label :ingredient, '成分' %>
          <%= f.text_area :ingredient, class: "item-text" %>
        </div>
        <div class="form">
          <%= f.label :made_in_id, '原産国' %>
          <%= f.collection_select(:made_in_id, MadeIn.all, :id, :name, {}, {class: "item-select"}) %>
        </div>
        <div class="form">
          <%= f.label :image, "商品画像アップロード", class:"image-btn" %>
          <%= f.file_field :image, class: "item-image" %>
        </div>
        <div class="submit">
          <%= f.submit "登録する", class:"submit-btn" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</main>
<%= render 'footer' %>