config/routes.rb
Rails.application.routes.draw do

  # ユーザー管理
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }
  resources :users, only: [:show]


  # 管理人用
  devise_for :admins
  namespace :admin do
    root to: 'admin/products#index'
    resources :products
  end


  # トップページ/詳細ページ/お気に入り
  root to: 'products#index'
  resources :products, only: [:index, :show] do
    resource :likes, only: [:create, :destroy]
  end

  
  # カート
  resources :carts, only: [:index] do
    collection do
      post :add
    end
    member do
      resources :cart_items, only: [:update, :destroy]
    end
  end


  # 購入
  resources :orders, only: [:new, :create]

end

app/models/product.rb
class Product < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to       :made_in
  has_one_attached :image
  has_many         :cart_items
  has_many         :likes, dependent: :destroy
  has_one          :order

  with_options presence: true do
    validates :name
    validates :price, format: { with: /\A[0-9]+\z/, message: '半角数字で入力してください' }
    validates :title
    validates :explanation
    validates :volume
    validates :ingredient
    validates :image
  end

  validates :made_in_id, numericality: { other_than: 1 }

  def liked?(user)
    likes.where(user_id: user.id).exists?
 end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :title, :explanation, :volume, :ingredient, :image, :made_in_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.order('created_at DESC')
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render "layouts/header" %>
<main>
  <div class="index-main">
    <%= image_tag "index.png", class: "main-image" %>
    <%= image_tag "bisui.png", class: "bisui" %>
    <p class="vertical">富士のめぐみで<br>清く美しく</p>
  </div>

  <div class="index-concept">
    <h1>Concept</h1>
    <div class="catchcopy">
      <h2>「たくさんのお祝い事が訪れますように」</h2>
      <h3>May Happiness Cometoyou</h3>
    </div>
    <p class="concept-text">
      豊かな大地、清らかな水<br>富士山の恵を存分にうけた日本酒の美容成分に着目し、<br>誰もが美しくなれる化粧品を。<br><br>
      「高砂」というおめでたい言葉にあやかって、<br>「美」と「幸せ」を結ぶ素敵な縁となるよう思いを込めました。
    </p>
  </div>

  <div class="index-collabo">
    <h1>Collaboration</h1>
    <div class="collabo-explain">
      <div class="collabo-image"><%= image_tag "syuzo.png", class: "syuzo" %></div>
      <div class="collabo-content">
        <p class="collabo-title">富士高砂酒造</p>
        <p class="collabo-text">
          天保元年創業。口当たりが優しく米の旨味が活かされた最高の美酒。
          それは100年の歳月をかけ、自然の濾過を施された天然水があってこそ。
          富士山とともに造られてきた日本酒たちは、今や世界中の人々を魅了しています。
        </P>
      </div>
    </div>
    <div class="collabo-explain">
      <div class="collabo-image"><%= image_tag "tsg_no6.png", class: "tsg" %></div>
      <div class="collabo-content">
        <p class="collabo-title">「TSG No.6」*</p>
        <p class="collabo-text">
          100年以上の歴史を持つ熟練の発酵技術を生かし、コメ発酵液のアミノ酸濃度を6倍まで高めた「TSG No.6」を独自開発。
          全ての化粧品にたっぷりと配合しています。
        </P>
        <p class="collabo-add">*保湿成分</p>
      </div>
    </div>
    <div class="catchcopy-back">
      <h2>お米に宿る、美のちから</h2>
      <p class="concept-text">
      お米を発酵させ抽出した「コメ発酵液」は<br>天然のアミノ酸を豊富に含んだ保湿成分。<br>角層の奥深くまで浸透し、保湿力やバリア機能を保つ<br>
      美肌に欠かせない守り神です。<br><br>コメ発酵液のアミノ酸濃度を<br>6倍まで高めた「TSG No.6」を独自開発し<br>全ての化粧品にたっぷりと配合しています。
     </p>
    </div>
  </div>

  <div class="index-products">
    <h1>Products</h1>
    <ul class="products-lists">
      <% @products.each do |product| %>
      <li class="list">
        <div class="product-image">
          <%= link_to image_tag(product.image, class:"image"), product_path(product.id) %>
        </div>
        <div class="product-info">
          <p class="product-name"><%= product.name %></p>
          <p class="product-price"><%= product.price.to_s(:delimited) %>円</p>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</main>
<%= render "layouts/footer" %>

app/views/products/show.html.erb
<%= render "layouts/header" %>
<main>
  <div class="show-wrap">
    <div class="show-colmn">
      <div class="show-top">
        <div class="show-image">
          <%= image_tag @product.image %>
        </div>
        <div class="show-info">
          <h3>Product Details</h3>
          <div class="show-detail">
            <p class="show-name"><%= @product.name %></p>
            <div class="show-flex">
              <p class="show-volume"><%= @product.volume %></p>
              <p class="show-price"><%= @product.price.to_s(:delimited) %>円(税込)</p>
            </div>
          </div>
          <p class="show-ingredient"><%= @product.ingredient %></p>
          <div class="show-cart">
            <div class="show-form">
            <%= form_with model: CartItem.new, url: add_carts_path, local: true do |f| %>
              数量：<%= f.text_field :quantity, value: 1, class:"show-quantity" %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.submit 'カートへ入れる', class:"show-submit" %>
              <% if user_signed_in? %>
                <span id="like_<%= @product.id %>">
                  <%= render "layouts/like", product: @product %>
                </span>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="show-bottom">
        <h2><%= @product.title %></h2>
        <p class="show-explanation"><%= safe_join(@product.explanation.split("\n"),tag(:br)) %></p>
        <p class="show-made-in">MADE IN <%= @product.made_in.name %></p>
      </div>
    </div>
  </div>
</main>
<%= render "layouts/footer" %>