config/routes.rb
Rails.application.routes.draw do

  # ユーザー管理
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }
  resources :users, only: [:show]


  # 管理人用
  devise_for :admins
  namespace :admin do
    root to: 'admin/products#index'
    resources :products
  end


  # トップページ/詳細ページ/お気に入り
  root to: 'products#index'
  resources :products, only: [:index, :show] do
    resource :likes, only: [:create, :destroy]
  end

  
  # カート
  resources :carts, only: [:index] do
    collection do
      post :add
    end
    member do
      resources :cart_items, only: [:update, :destroy]
    end
  end


  # 購入
  resources :orders, only: [:new, :create]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

# 削除
#  :registerable サインアップ処理
#  :recoverable  パスワードリセット

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many   :cart_items, dependent: :destroy

  def total_price
    cart_items.sum do |item|
      item.quantity * item.product.price
    end
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :product
  
  validates :quantity, presence: true,
                       numericality: {
                        only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 30,
                        message: "半角数字で入力してください(30個まで)"}

end

app/models/destination.rb
class Destination < ApplicationRecord
  has_one    :order
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

  # with_options presence: true do
  #   validates :last_name
  #   validates :first_name
  #   validates :post_code, format: { with: /\A\d{3}[-]\d{4}\z/, message: '半角数字でハイフン(-)を入れて入力してください' }
  #   validates :city
  #   validates :address, format: { with: /\A[0-9]+\z/, message: '半角数字で入力してください' }
  #   validates :phone, format: { with: /\A\d{10,11}\z/, message: '半角数字で入力してください(ハイフンなし)' }
  # end

  # validates :prefecture_id, numericality: { other_than: 1 }
end

app/models/destination_order.rb
class DestinationOrder
  include ActiveModel::Model
  attr_accessor :last_name, :first_name, :post_code, :city, :address, :building, :phone, :prefecture_id, :user_id, :token

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :post_code, format: { with: /\A\d{3}[-]\d{4}\z/, message: '半角数字でハイフン(-)を入れて入力してください' }
    validates :city
    validates :address, format: { with: /\A[0-9]+\z/, message: '半角数字で入力してください' }
    validates :phone, format: { with: /\A\d{10,11}\z/, message: '半角数字で入力してください(ハイフンなし)' }
    validates :user_id
    # validates :charge_id
    # validates :sold_at
    # validates :order_code
    validates :token
  end
              
  validates :prefecture_id, numericality: { other_than: 1 }

  def save
    destination = Destination.create(
      last_name: last_name,
      first_name: first_name,
      post_code: post_code,
      city: city,
      address: address,
      building: building,
      phone: phone,
      prefecture_id: prefecture_id)

    Order.create(
      user_id: user_id,
      destination_id: destination.id
      # charge_id: charge_id,
      # order_code: SecureRandom.uuid,
      # sold_at: Time.new  
    )
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/made_in.rb
class MadeIn < ActiveHash::Base
  self.data = [
    { id: 1, name: '▽'},
    { id: 2, name: 'JAPAN'}
  ]

  include ActiveHash::Associations
  has_many :products

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :destination
  has_many   :order_items
  # accepts_nested_attributes_for :destination

  # with_options presence: true do
  #   validates :sold_at,
  #   validates :charge_id,
  #   validates :order_code
  # end

  def assign_from_cart(cart)
    cart.cart_items.each do |item|
      order_items << OrderItem.new(
        product_id: item.product_id,
        quantity: item.quantity,
        price_with_tax: item.quantity * item.product.price,
        price: item.quantity * item.product.price / 1.1,
      )
    end
    cart.destroy
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  with_options presence: true do
    validates :quantity
    validates :price
    validates :price_with_tax
  end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1,  name: '都道府県を選択' },
    { id: 2,  name: '北海道' },
    { id: 3,  name: '青森県' },
    { id: 4,  name: '岩手県' },
    { id: 5,  name: '宮城県' },
    { id: 6,  name: '秋田県' },
    { id: 7,  name: '山形県' },
    { id: 8,  name: '福島県' },
    { id: 9,  name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :destinations
end

app/models/product.rb
class Product < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to       :made_in
  has_one_attached :image
  has_many         :cart_items
  has_many         :likes, dependent: :destroy
  has_one          :order

  with_options presence: true do
    validates :name
    validates :price, format: { with: /\A[0-9]+\z/, message: '半角数字で入力してください' }
    validates :title
    validates :explanation
    validates :volume
    validates :ingredient
    validates :image
  end

  validates :made_in_id, numericality: { other_than: 1 }

  def liked?(user)
    likes.where(user_id: user.id).exists?
 end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_one :destination
  has_many :likes


  with_options presence: true do
    validates :nickname
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
      <div class="foot-contents">
        <div class="foot-content1">
          <%= link_to image_tag("logo2.png", class:"foot-logo"), '#' %>
          <ul class="foot-nav1">
            <li><%= link_to 'Shopping guide', '#', class:"guide-nav" %></li>
            <li><%= link_to 'Company', '#', class:"company-nav" %></li>
          </ul>
        </div>
        <div class="foot-content2">
          <ul class="foot-nav2">
            <li><%= link_to '個人情報保護方針', '#', class:"privacy-nav" %></li>
            <li><%= link_to '特定商取引法に基づく表示', '#', class:"law-nav" %></li>
            <li><%= link_to '管理ページ', admin_products_path, class:"admin-nav" %></li>
          </ul>
        </div>
      </div>
      <div class="foot-bar">
        <p class="copyright">©日本酒化粧品の通販・ギフト｜ふじのふもとの姫beauty all right reserved.</p>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<header>
  <div class="head-bar">
    <%= link_to image_tag("logo1.png", class:"head-logo"), root_path %>
    <ul class="head-nav">
      <li><%= link_to 'Products', '#', class:"product-nav" %></li>
      <li><%= link_to 'Contact', '#', class:"contact-nav" %></li>
      <% if user_signed_in? %>
        <li><%= link_to image_tag("mypage_logo.png", class:"mypage-nav"), user_path(current_user.id) %></li>
      <% else %>
        <li><%= link_to image_tag("mypage_logo.png", class:"mypage-nav"), new_user_session_path %></li>
      <% end %>
      <li>
        <%= link_to image_tag("cart_logo.png", class:"cart-nav"), carts_path %>
        <%# if Cart.find_by(user_id: current_user.id).present? %>
          <!--<span class="circle"><i class="fa-solid fa-heart"></i></span>-->
        <%# end %>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/_like.html.erb
<% if product.liked?(current_user) %>
  <%= link_to product_likes_path(product.id), method: :delete, remote: true do %>
    <i class="fa-solid fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to product_likes_path(product.id), method: :post, remote: true do %>
    <i class="fa-regular fa-heart"></i>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HimebeautyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>@import url("https://use.typekit.net/ewq8qjz.css");</style>
    <script>
      (function(d) {
        var config = {
          kitId: 'yvg7uij',
          scriptTimeout: 3000,
          async: true
        },
        h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
      })(document);
    </script>
    <link rel="stylesheet" href="https://use.typekit.net/ewq8qjz.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>